### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by JoshuaPerk** [jekorx/particle-wave#14]
How would one go about changing the color of the wave? If I wanted to make one end of the gradient pink and the other purple?

**Comment by jekorx** [comment]
> How would one go about changing the color of the wave? If I wanted to make one end of the gradient pink and the other purple?

![image](https://github.com/user-attachments/assets/b968d38f-f646-403d-b7db-7df343215658)

onResize function，you can write your rgb color here
