### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by dragszymon** [jekorx/particle-wave#6]
Hi 🖐🏻

Thanks for sharing such an awesome script ❤️

I'm using it on the main page of my website. I built it using Nuxt.js. I noticed that even if a component/div that ParticleWave is built upon is destroyed the instance of the class is still performing calculations in the background. I'm afraid that this is cousing low performance of my site.

Is there a chance of adding a some kind of destroy method?

**Comment by jekorx** [comment]
Thanks for your feedback, which will be added in future versions.

**Comment by jekorx** [comment]
Clear method is supported from [particle-wave@1.0.6](https://www.npmjs.com/package/particle-wave/v/1.0.6).
